---
functional:
  - требование Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - требование Пользователь должен иметь возможность фильтровать товары
  - требование Пользователь должен иметь возможность просматривать товары и просматривать подробную 
  информацию о товаре
  - требование Пользователь должен иметь возможность добавлять товары в корзину и просматривать 
  содержимое корзины
non-functional:
  - требование Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - требование Сайт должен иметь мобильную версию
  - требование Сайт нужно протестировать на совместимость с последними версиями браузеров
  - требование Сайт должен быть доступен на различных устройствах
  - требование Сайт должен быть безопасным и защищать данные пользователя
  - требование Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - при обновлении страницы список товара в корзине должен остоваться без изменений
  - должен быть телефон пользователя для обратной связи
