---
functional:
  - требование 3
  - требование 4
  - требование 8
  - требование 9
non-functional:
  - требование 1
  - требование 5
  - требование 6
  - требование 10
implicit:
  - требование 2
  - требование 7
  - при обновлении страницы список товара в корзине должен остоваться без изменений
  - должен быть телефон пользователя для обратной связи
